---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list: 
      - recipe[awesome]
    attributes:
      apache:
        default_site_enabled: true
